# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea2784f251ba686c67ccd644bf710218603eb87f4e64c093a610b41934f973ec53f3d76c6911d3c250fe469188b7fc2d4bef3e64dd897420e5f54912f22744a

test:
  secret_key_base: b57b4c5bf2ca049cadc6f8bcd620e9d95839967f908c74dcf51b21b743304274ec60d4653e9f880a0786af81c3cbee40a0746d70999dec88f07d72dc535c6f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
